config/routes.rb
Rails.application.routes.draw do
  
  if Rails.env.development?
    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  end

  root 'welcome#index'

  devise_for :users, :controllers => { omniauth_callbacks: 'authentications' },
    path: '', path_names: {sign_in: 'login', sign_out: 'logout'}

end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
  # Relations
  belongs_to :user

  validates_presence_of :user 
  validates :user, uniqueness: true

    # Class methods
  def self.user_from_omniauth(omniauth)

    authentication = where(provider: omniauth.provider, uid: omniauth.uid)
      .first_or_create do |auth|
        # assign user
        auth.user = User.new(provider: omniauth.provider)
        auth.user.email = omniauth.info.email.blank? ? "placeholder@demo.de" : omniauth.info.email
        auth.user.password = Devise.friendly_token[0,20]
        auth.user.username = "user_#{User.all.length}_#{Devise.friendly_token[0,5]}"
        auth.user.save!
        # assign attributes
        auth.secret = omniauth.credentials.secret
        auth.token =  omniauth.credentials.token

        if omniauth.credentials.refresh_token!=nil
          auth.refresh_token=omniauth.credentials.refresh_token
        end

        if omniauth.credentials.expires_at.present?
          auth.expires_at = Time.at(omniauth.credentials.expires_at.to_i)
        end
      end

    authentication.user
  end 

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :omniauthable,
         :recoverable, :rememberable, :trackable, :validatable, :authentication_keys => [:login]

  has_one :authentication

  attr_accessor :login

  def login=(login)
    @login = login
  end

  def login
    @login || self.username
  end

  def email_required?
    false
  end

  def email_changed?
    false
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/authentications_controller.rb
class AuthenticationsController < Devise::OmniauthCallbacksController

  def facebook
    apply_omniauth("Facebook", "devise.facebook_data")
  end

  def google_oauth2
    apply_omniauth("Google", "devise.google_data")
  end

  def twitter
    apply_omniauth("Twitter", "devise.twitter_data")
  end

  def pinterest
    apply_omniauth("Pinterest", "devise.pinterest_data")
  end

  def instagram
    apply_omniauth("Instagram", "devise.instagram_data")
  end



  def apply_omniauth(provider, session_data)

    if current_user.present?

        redirect_to root_path

    else

      @user = Authentication.user_from_omniauth(request.env["omniauth.auth"])
    
      if @user.persisted?
        sign_in_and_redirect @user, :event => :authentication
      else
        session[session_data] = request.env["omniauth.auth"]
        redirect_to root_path
      end

    end  
  end  

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  require 'google/apis/youtube_v3'
  require 'google/apis/youtube_analytics_v1'
  require 'googleauth'
  require 'googleauth/token_store'

  def index
    if current_user.present?
      provider = current_user.authentication.provider
      @answer = query_provider(provider)
    end
  end


private

  def query_provider(provider)
   return query_facebook if provider == "facebook"
   return query_youtube if provider == "google_oauth2"
   return query_instagram if provider == "instagram"
   return query_twitter if provider == "twitter"
   return query_pinterest if provider == "pinterest"
  end


  def query_facebook
   token = current_user.authentication.token
   api = Koala::Facebook::API.new(token)
   api.get_object("me/posts").as_json
  end

  def query_youtube

    scope = GOOGLE_YT_SCOPE
    client_id = Google::Auth::ClientId.new(GOOGLE_CLIENT_ID, GOOGLE_CLIENT_SECRET)
    token_store = YoutubeTokenStore.new

    authorizer = Google::Auth::UserAuthorizer.new(client_id, scope, token_store)

    credentials = authorizer.get_credentials(current_user.id)
    client =  Google::Apis::YoutubeV3::YouTubeService.new

    if credentials.nil?
      url = authorizer.get_authorization_url(base_url: OOB_URI )
      puts "Open #{url} in your browser and enter the resulting code:"
      code = gets
      credentials = authorizer.get_and_store_credentials_from_code(
        user_id: user_id, code: code, base_url: OOB_URI)
    end
    
    client.authorization=credentials

    client.list_channels('snippet,id', mine: true).as_json
  end

  def query_instagram
    client = Instagram.client(:access_token => current_user.authentication.token)
    
    client.user_recent_media.as_json
  end

  def query_twitter

    authentication=current_user.authentication

    client = Twitter::REST::Client.new do |config|
      config.consumer_key        = TWITTER_ID
      config.consumer_secret     = TWITTER_SECRET
      config.access_token        = authentication.token
      config.access_token_secret = authentication.secret
    end

    client.home_timeline.as_json
  end

  def query_pinterest
    authentication = current_user.authentication
    client = Pinterest::Client.new(authentication.token)
    
    client.get_pins({:fields=>"board, id, counts, image, note, created_at, url", :limit => 20 }).as_json
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title SocialMediaApisDemo
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    %meta{name: 'viewport', content: 'width=device-width, initial-scale=1.0, minimum-scale=1, maximum-scale=1'}
    = csrf_meta_tags

  %body
    .container
      = yield

app/views/welcome/index.html.haml
.row
  .col-xs-12 
    %h1
      Toptal Social Media APIs Demo
    - flash.each do |key, value|
      = content_tag :div, value, class: "flash #{key}"
- if current_user.present?
  .row
    .col-xs-12
      = "logged in with #{current_user.authentication.provider}"
      = link_to t(".logout"), destroy_user_session_path, method: :delete , class: "btn btn-destroy"
  .row
    .col-xs-12
      = "answer: #{@answer}"   
- else 
  %br
  .row
    .col-xs-4
      = link_to t(".login_with_facebook"), omniauth_authorize_path('user', :facebook), class: "btn btn-primary"
    .col-xs-4
      = link_to t(".login_with_instagram"), omniauth_authorize_path('user', :instagram), class: "btn btn-primary"
    .col-xs-4
      = link_to t(".login_with_google"), omniauth_authorize_path('user', :google_oauth2), class: "btn btn-primary"
  %br
  .row
    .col-xs-4
      = link_to t(".login_with_twitter"), omniauth_authorize_path('user', :twitter), class: "btn btn-primary"
    .col-xs-4
      = link_to t(".login_with_pinterest"), omniauth_authorize_path('user', :pinterest), class: "btn btn-primary"